# -*- coding: utf-8 -*-
"""roomallotment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Merh8x4t_Xg5vlBXO6vkzF8RUK12X_T1
"""

rooms = {
    101: None,
    102: None,
    103: None,
    104: None,

    105: None,
    106: None,
    107: None,
    108: None,
    109: None,
    110: None
}
occupied = set()
n=int(input("enter the number of student you want:"))
for i in range(n):
  name=input("enter the name of the student")
  alloted = False
  for room_no in rooms:
    if rooms[room_no] is None:
      rooms[room_no] = name
      occupied.add(room_no)
      print(f"{name} has been alloted room number {room_no}")
      alloted = True
      break
    if not alloted:
       print("sorry all the rooms are occupied")
  print("\nFinal Room Allotment:")
for room_no, student in rooms.items():
    print(room_no, "-", student)
print("\nOccupied Rooms:", occupied)